Api/assignments
theusaf/osu-cs493-final-project pull request #44
Opened 2024-06-09 19:48 UTC by Padraic-0

Get and Post submissions

2024-06-09 19:55 UTC, theusaf requested changes

2024-06-09 19:55 UTC, theusaf commented on src/api/assignments.ts
> +  const submission = new Submission(submissionData);
> The grade, in points, assigned to the student for this sumbission, if one is assigned. Should not be accepted during submission creation, only via update.

2024-06-09 19:55 UTC, theusaf commented on src/api/assignments.ts
> +router.post("/:id/submissions", requireAuthentication({
This route should also require certain body inputs. It should also save the incoming file to disk or cloud storage.

2024-06-09 19:55 UTC, theusaf commented on src/api/assignments.ts
> +    submissions: submissions,
Be sure to send back data using the `.toJSON()` to avoid potential issues

2024-06-09 19:55 UTC, theusaf commented on src/api/assignments.ts
> +    submissions: submissions,
In addition, the response should contain URLs to the files in the submissions

2024-06-10 18:04 UTC, theusaf requested changes

2024-06-10 18:04 UTC, theusaf commented on src/models/submissions.ts
Considering the data saved is a buffer, the return of the `toJSON` should return a URL instead. Also, the `save` method should be overridden to save the buffer to the storage bucket / firestore.
To do this, consider adding a `fileURL` or `fileId` to be able to access  the file data at a later point. (Or design the save system to use the id of the submission).

2024-06-10 18:13 UTC, theusaf approved these changes

2024-06-10 18:17 UTC, Padraic-0 commented on src/models/submissions.ts
Im not sure what that means

2024-06-10 18:38 UTC, theusaf approved these changes

2024-06-10 18:39 UTC, merged